  /* DWARF 5.  */
  .debug_addr   :
  {
    *(.debug_addr)
  }
  .zdebug_addr   :
  {
    *(.zdebug_addr)
  }
  .debug_line_str   :
  {
    *(.debug_line_str)
  }
  .zdebug_line_str   :
  {
    *(.zdebug_line_str)
  }
  .debug_loclists   :
  {
    *(.debug_loclists)
  }
  .zdebug_loclists   :
  {
    *(.zdebug_loclists)
  }
  .debug_macro   :
  {
    *(.debug_macro)
  }
  .zdebug_macro   :
  {
    *(.zdebug_macro)
  }
  .debug_names   :
  {
    *(.debug_names)
  }
  .zdebug_names   :
  {
    *(.zdebug_names)
  }
  .debug_rnglists   :
  {
    *(.debug_rnglists)
  }
  .zdebug_rnglists   :
  {
    *(.zdebug_rnglists)
  }
  .debug_str_offsets   :
  {
    *(.debug_str_offsets)
  }
  .zdebug_str_offsets   :
  {
    *(.zdebug_str_offsets)
  }
  .debug_sup   :
  {
    *(.debug_sup)
  }